comport: COM3
baudrate: 9600
bytesize: 8
parity: N
stopbits: 1
vm: false
vmversion: banana
Mappings:
  "1":
    ProcessNames: []
    VoiceMeeter: null
  "2":
    ProcessNames: []
    VoiceMeeter: null
  "3":
    ProcessNames:
      - Spotify.exe
    VoiceMeeter: null
  "4":
    ProcessNames:
      - Plex.exe
      - firefox.exe
    VoiceMeeter: null
