comport: COM9
baudrate: 9600
bytesize: 8
parity: N
stopbits: 1
Mappings:
  "1":
    ProcessNames:
      - master
    VoiceMeeter: null
  "2":
    ProcessNames:
      - steam.exe
    VoiceMeeter: null
  "3":
    ProcessNames:
      - Spotify.exe
    VoiceMeeter: null
  "4":
    ProcessNames:
      - firefox.exe
    VoiceMeeter: null
vm: false
vmversion: banana
