comport: COM9
baudrate: 9600
bytesize: 8
parity: N
stopbits: 1
vm: false
vmversion: banana
Mappings:
  "1":
    ProcessNames: [Discord.exe]
    VoiceMeeter: ""
  "2":
    ProcessNames: [master]
    VoiceMeeter: Input1
  "3":
    ProcessNames:
      -
    VoiceMeeter: Output1
  "4":
    ProcessNames: []
    VoiceMeeter: ""
